language: ruby

cache:
  directories:
    - $HOME/.evm

before_install:
  - chmod a+x ./scripts/*.sh
  - (cd $HOME/.evm && git pull) || git clone https://github.com/rejeep/evm.git $HOME/.evm
  - export PATH=$HOME/.evm/bin:$PATH
  - evm config path /tmp
  - evm install $EVM_EMACS --use --skip

env:
  - EVM_EMACS=emacs-26.2-travis
  #- EVM_EMACS=emacs-git-snapshot-travis

matrix:
  allow_failures:
    - env: EVM_EMACS=emacs-git-snapshot-travis

script:
  lsb_release -a && ./scripts/startup.sh

# Local Variables:
# indent-tabs-mode: nil
# coding: utf-8
# End: